PYTHON3 ?= python3.7

check:
	$(PYTHON3) ./test_mount.py
	$(PYTHON3) ./test_mnt_is_dir.py
	$(PYTHON3) ./test_empty_dir.py
	$(PYTHON3) ./test_flat_dir.py
	$(PYTHON3) ./test_flat_file.py
	$(PYTHON3) ./test_hier_dir.py
	$(PYTHON3) ./test_hier_file.py
	$(PYTHON3) ./test_name_check_file_first_dir.py
	$(PYTHON3) ./test_name_check_dir_first_file.py
	$(PYTHON3) ./test_name_check_same_file_dir.py
	$(PYTHON3) ./test_name_check_same_file_file.py
	$(PYTHON3) ./test_flat_file_io_write.py
	$(PYTHON3) ./test_flat_file_io_append.py
